# Generated by Django 3.2.7 on 2021-10-03 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('imported_t', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('TRASH', 'TRASH'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=50, verbose_name='Status')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=50, verbose_name='Gender')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('first', models.CharField(max_length=50, verbose_name='First')),
                ('last', models.CharField(max_length=50, verbose_name='Last')),
                ('street_number', models.IntegerField(default=None, verbose_name='Street Number')),
                ('street_name', models.CharField(max_length=50, verbose_name='Street Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('postcode', models.IntegerField(default=None, verbose_name='Postcode')),
                ('latitude', models.CharField(default=None, max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(default=None, max_length=50, verbose_name='Longitude')),
                ('offset', models.CharField(default=None, max_length=50, verbose_name='Offset')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('email', models.EmailField(default=None, max_length=50, verbose_name='Email')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('salt', models.CharField(max_length=50, verbose_name='Salt')),
                ('md5', models.CharField(max_length=100, verbose_name='MD5')),
                ('sha1', models.CharField(max_length=100, verbose_name='SHA1')),
                ('sha256', models.CharField(max_length=100, verbose_name='SHA256')),
                ('dob_date', models.DateTimeField(default=None, verbose_name='Dob Date')),
                ('dob_age', models.IntegerField(default=None, verbose_name='Dob Age')),
                ('registered_date', models.DateTimeField(default=None, verbose_name='Registered Date')),
                ('registered_age', models.IntegerField(default=18, verbose_name='Registered Age')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('cell', models.CharField(max_length=20, verbose_name='Cell')),
                ('id_name', models.CharField(max_length=30, verbose_name='ID Name')),
                ('id_value', models.CharField(max_length=50, verbose_name='ID Value')),
                ('picture_large', models.TextField(max_length=100, verbose_name='Picture Large')),
                ('picture_medium', models.TextField(max_length=70, verbose_name='Picture Medium')),
                ('picture_thumbnail', models.TextField(max_length=50, verbose_name='Picture Thumbnail')),
                ('nat', models.CharField(max_length=30, verbose_name='Nat')),
                ('seed', models.CharField(default=None, max_length=70, verbose_name='Seed')),
            ],
        ),
    ]
