# Generated by Django 3.2.7 on 2021-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='postcode',
            field=models.IntegerField(default=None, verbose_name='Postcode'),
        ),
    ]
