# Generated by Django 3.2.7 on 2021-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='imported_t',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
