# Generated by Django 3.2.7 on 2021-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='latitude',
            field=models.CharField(default=None, max_length=50, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='longitude',
            field=models.CharField(default=None, max_length=50, verbose_name='Longitude'),
        ),
    ]
