# Generated by Django 3.2.7 on 2021-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cell',
            field=models.CharField(max_length=9, verbose_name='Cell'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=8, verbose_name='Phone'),
        ),
    ]
