# Generated by Django 3.2.7 on 2021-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211003_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='offset',
            field=models.CharField(default=None, max_length=50, verbose_name='Offset'),
        ),
    ]
