# Generated by Django 3.2.7 on 2021-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211003_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='imported_t',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
