# Generated by Django 3.2.7 on 2021-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='seed',
            field=models.CharField(default=None, max_length=70, verbose_name='Seed'),
        ),
    ]
