# Generated by Django 3.2.7 on 2021-10-24 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211024_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('points', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pointsuser'),
        ),
    ]
