# Generated by Django 3.2.7 on 2021-10-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211024_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='user.pointsuser'),
        ),
    ]
