# Generated by Django 3.2.7 on 2021-10-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pointsuser'),
        ),
    ]
