from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.permissions import IsAuthenticated

from .models import UserModel
from .serializer import UserSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = UserModel.objects.all()
    serializer_class = UserSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    filter_backends = (SearchFilter, DjangoFilterBackend, OrderingFilter)

    search_fields = (
        "pk",
        "imported_t",
        "status",
        "gender",
        "first",
        "last",
        "street_number",
        "street_name",
        "city",
        "state",
        "postcode",
        "latitude",
        "longitude",
        "offset",
        "description",
        "email",
        "uuid",
        "username",
        "password",
        "salt",
        "md5",
        "sha1",
        "sha256",
        "dob_date",
        "dob_age",
        "registered_date",
        "registered_age",
        "phone",
        "cell",
        "id_name",
        "id_value",
        "picture_large",
        "picture_medium",
        "picture_thumbnail",
        "nat",
        "seed",
    )
    filter_fields = (
        "pk",
        "imported_t",
        "status",
        "gender",
        "first",
        "last",
        "street_number",
        "street_name",
        "city",
        "state",
        "postcode",
        "latitude",
        "longitude",
        "offset",
        "description",
        "email",
        "uuid",
        "username",
        "password",
        "salt",
        "md5",
        "sha1",
        "sha256",
        "dob_date",
        "dob_age",
        "registered_date",
        "registered_age",
        "phone",
        "cell",
        "id_name",
        "id_value",
        "picture_large",
        "picture_medium",
        "picture_thumbnail",
        "nat",
        "seed",
        )
    ordering_fields = (
        "pk",
        "imported_t",
        "status",
        "gender",
        "first",
        "last",
        "street_number",
        "street_name",
        "city",
        "state",
        "postcode",
        "latitude",
        "longitude",
        "offset",
        "description",
        "email",
        "uuid",
        "username",
        "password",
        "salt",
        "md5",
        "sha1",
        "sha256",
        "dob_date",
        "dob_age",
        "registered_date",
        "registered_age",
        "phone",
        "cell",
        "id_name",
        "id_value",
        "picture_large",
        "picture_medium",
        "picture_thumbnail",
        "nat",
        "seed",
    )
    ordering = (
        "pk",
        "imported_t",
        "status",
        "gender",
        "first",
        "last",
        "street_number",
        "street_name",
        "city",
        "state",
        "postcode",
        "latitude",
        "longitude",
        "offset",
        "description",
        "email",
        "uuid",
        "username",
        "password",
        "salt",
        "md5",
        "sha1",
        "sha256",
        "dob_date",
        "dob_age",
        "registered_date",
        "registered_age",
        "phone",
        "cell",
        "id_name",
        "id_value",
        "picture_large",
        "picture_medium",
        "picture_thumbnail",
        "nat",
        "seed",
    )
